#!/usr/bin/python3

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo

if __import__('os').getenv('REMOTE_DEBUG', "Off") == "On":    
    import ptvsd
    ptvsd.enable_attach(('0.0.0.0', 3333))

if __name__ == "__main__":
    odoo.cli.main()